---
- name: Deploy do Apache e MySQL no Docker via Ansible
  hosts: all
  become: true
  vars:
    apache_dir: /home/ubuntu/desafio-terraform-novo/apache
    mysql_dir: /home/ubuntu/desafio-terraform-novo/mysql
    html_dir: /home/ubuntu/desafio-terraform-novo/apache/public-html

  tasks:
    - name: Criar diretórios
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - "{{ html_dir }}"
        - "{{ apache_dir }}"
        - "{{ mysql_dir }}"

    - name: Criar arquivo index.html para teste
      copy:
        content: "<h1>Servidor Apache funcionando!</h1>"
        dest: "{{ html_dir }}/index.html"
        mode: '0644'

    - name: Remover container Apache existente (se houver)
      community.docker.docker_container:
        name: apache_container
        state: absent
        force_kill: true

    - name: Remover container MySQL existente (se houver)
      community.docker.docker_container:
        name: mysql_container
        state: absent
        force_kill: true

    - name: Build da imagem do Apache
      community.docker.docker_image:
        name: apache-custom
        source: build
        build:
          path: "{{ apache_dir }}"

    - name: Build da imagem do MySQL
      community.docker.docker_image:
        name: mysql-custom
        source: build
        build:
          path: "{{ mysql_dir }}"

    - name: Subir container Apache
      community.docker.docker_container:
        name: apache_container
        image: apache-custom
        state: started
        ports:
          - "80:80"
        volumes:
          - "{{ html_dir }}:/var/www/html"

    - name: Subir container MySQL
      community.docker.docker_container:
        name: mysql_container
        image: mysql-custom
        state: started
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: metroid
          MYSQL_DATABASE: meubanco
          MYSQL_USER: admin
          MYSQL_PASSWORD: metroid
