---
- name: Deploy do MySQL no Docker via Ansible
  hosts: servers
  become: true
  tasks:
    - name: Criar container MySQL
      docker_container:
        name: mysql_container
        image: mysql:latest
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: desafio
          MYSQL_USER: admin
          MYSQL_PASSWORD: metroid
        ports:
          - "3306:3306"
        volumes:
          - "/home/ubuntu/desafio-terraform-novo/mysql_data:/var/lib/mysql"

